type Book {
    id: ID!
    title: String!
    shelfNo: String!
    #author: String!
    #publishDate: String!
}

type Query {
    books: [Book!]!
}

type Mutation {
    createBook(title: String!, shelfNo: String!): Book!
    deleteBook(id: ID!): Book!
}